version: "3.9"
services:
  bd:
    image: "mcr.microsoft.com/mssql/server"
    container_name: bd_clientes
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Upt.2022
    volumes:
      - ./db:/tmp
    networks:
      - gestion_clientes_network
      - bitacora_gestion_clientes_network

  api:
    build: ClienteAPI/.
    container_name: api_clientes
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__ClienteDB=Server=bd;Database=BD_CLIENTES;User Id=sa;Password=Upt.2022;TrustServerCertificate=true
    depends_on:
      - bd
    networks:
      - gestion_clientes_network
      - bitacora_gestion_clientes_network

networks:
  gestion_clientes_network:
    external: true
  bitacora_gestion_clientes_network:
    external: true
