version: '3.8'
services:
  app:
    build: .
    container_name: bitacora_api
    environment:
      RabbitMQ__HostName: 161.132.37.246
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      MongoDB__ConnectionString: mongodb+srv://jeanvalverde:Valverde24@jeancluster.qdtfszz.mongodb.net/?retryWrites=true&w=majority
      MongoDB__DatabaseName: BDII
      MongoDB__CollectionName: uptBDII
    ports:
      - "5001:80"
